name: wf-cd-development
on:
  push:
    branches:
      - develop
jobs:
  cd-build-development-job:
    runs-on: ubuntu-latest 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Create Build Artifacts
        run: |
          npx parcel build "./src/index.html" --distidir "./dist" --public-url "./"
      - name: Upload Development Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "development-artifact"
  cd-deploy-development-job:
    needs: "cd-build-development-job"
    environment: "development-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Artfifacts
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "developmet_artifact"
          token: ${{github.token}}                   