name: wf-ci-development
on:
  pull_request:
    - develop
jobs:
  ci-development-jobs:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint HTML and CSS code
        run: |
          npx htmlhint "**/*.html" 
          npx stylelint "**/*.css"
      - name: Test Build
        run: |
          npX parcel build "./src/index.html: --dist-dir "./dist" --public-url "./"
